#!/usr/bin/env python3

import os
from pathlib import Path
import subprocess as sp

WORK_DIR = Path(__file__).parent

sp.run(["docker", "build",
    "--build-arg", f"HOST_GID={os.getegid()}",
    "--build-arg", f"HOST_UID={os.geteuid()}",
    "--tag", "thoughts",
    ".",
], cwd=WORK_DIR, check=True)
