#!/usr/bin/env python3

import os
from pathlib import Path
import subprocess as sp

host_work_dir = Path(os.getcwd())
sp.run(["docker", "run",
    "--env", "THOUGHTS_CONFIG=thoughts.cfg",
    "--interactive",
    "--name", "thoughts",
    "--publish", "5000:5000",
    "--publish", "9500:9500",
    "--rm",
    "--tty",
    "--user", "user",
    "--volume", f"{host_work_dir}:/workdir:rw",
    "--volume", f"{host_work_dir}/.m2:/home/user/.m2:rw",
    "--workdir", "/workdir",
    "thoughts",
    "/bin/sh",
], check=True)
