#!/usr/bin/env python3

import os
from pathlib import Path
import subprocess as sp

host_work_dir = Path(os.getcwd())
sp.run(["docker", "run",
    "--interactive",
    "--name", "thoughts",
    "--publish", "5000:5000",
    "--rm",
    "--tty",
    "--volume", f"{host_work_dir}:/workdir:rw",
    "--workdir", "/workdir",
    "thoughts",
    "./app",
], check=True)
